name: BuildContainerImage

on:
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*'
  workflow_dispatch: # Manual trigger

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to ALIYUN
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Login to DOCKER
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Chose Registry by tag
        id: chose_registry
        run: |
          if [[ ${GITHUB_REF#refs/*/} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "env=prod" >> "$GITHUB_OUTPUT"
          else
              echo "env=dev" >> "$GITHUB_OUTPUT"
          fi
          echo "tag=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"          

      - name: Build and push ks-apiserver images
        uses: docker/build-push-action@v6
        if: steps.chose_registry.outputs.env == 'prod'
        with:
          context: ${{ github.workspace }}
          file: build/ks-apiserver/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}

      - name: Build and push ks-controller-manager images
        uses: docker/build-push-action@v6
        if: steps.chose_registry.outputs.env == 'prod'
        with:
          context: ${{ github.workspace }}
          file: build/ks-controller-manager/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}
      
      - name: Sync ks images to ALIYUN
        if: steps.chose_registry.outputs.env == 'prod'
        run: |
          # apiserver
          docker pull --platform linux/amd64 docker.io/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}
          docker tag docker.io/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-amd64
          docker push registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-amd64
          docker pull --platform linux/arm64 docker.io/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}
          docker tag docker.io/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-arm64
          docker push registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-arm64
          docker manifest create registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-arm64 registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-amd64
          docker manifest annotate registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-arm64 --os linux --arch arm64
          docker manifest annotate registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}-amd64 --os linux --arch amd64
          docker manifest push registry.cn-beijing.aliyuncs.com/kubesphereon/ks-apiserver:${{ steps.chose_registry.outputs.tag }}
          # controller-manager
          docker pull --platform linux/amd64 docker.io/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}
          docker tag docker.io/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-amd64
          docker push registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-amd64
          docker pull --platform linux/arm64 docker.io/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}
          docker tag docker.io/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-arm64
          docker push registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-arm64
          docker manifest create registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-arm64 registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-amd64
          docker manifest annotate registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-arm64 --os linux --arch arm64
          docker manifest annotate registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }} registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}-amd64 --os linux --arch amd64
          docker manifest push registry.cn-beijing.aliyuncs.com/kubesphereon/ks-controller-manager:${{ steps.chose_registry.outputs.tag }}
          
